// Domain types for the UI, derived from the backend's OpenAPI schema
// (lib/generated/schema.ts, regenerated by `npm run gen:api`). These used to be
// hand-kept mirrors of the backend contracts; they are now aliases of the
// generated schema, so a backend change surfaces as a frontend type error rather
// than silent drift. Only genuinely client-side projections (PlanTask,
// TaskReflection) and the small terminal-state constants are defined by hand.

import type { components } from "./generated/schema";

type Schemas = components["schemas"];

// --- Run + event contracts -------------------------------------------------

export type RunStatus = Schemas["RunStatus"];

export const TERMINAL_STATUSES: RunStatus[] = ["done", "failed", "cancelled"];

export type RunView = Schemas["RunView"];

// Compact run row for the History list (GET /runs).
export type RunSummary = Schemas["RunSummary"];

export type ToolSpec = Schemas["ToolSpec"];

// The event stream carries the schema's known types, but the WebSocket is
// forward-compatible: a future backend may emit a type this client predates, so
// the union stays open (matching the reducer's `default` handling). `string & {}`
// keeps literal autocomplete while allowing any string.
export type EventType = Schemas["EventType"] | (string & {});

// One ledger event as consumed by the reducer/feed. Derived from the schema's
// `Event`, but `payload` and `ts` are always present on the wire (the schema
// marks them optional because they carry server defaults), so they are pinned
// here to keep call sites free of needless `?.` guards.
export type RunEvent = Omit<Schemas["Event"], "payload" | "ts" | "type"> & {
  type: EventType;
  payload: Record<string, unknown>;
  ts: string;
};

export const TERMINAL_EVENT_TYPES: EventType[] = [
  "run.completed",
  "run.failed",
  "run.cancelled",
];

// --- Task list (M3/M4) -----------------------------------------------------

export type TaskStatus = Schemas["TaskStatus"];

// A reflection verdict attached to a task for display (M4). Client-side
// projection of task.reflected event payloads — not a backend DTO.
export interface TaskReflection {
  decision: string; // accept | retry | replan | abort
  reason: string;
  attempt: number;
}

// The checklist row the UI maintains by folding events (ADR-0009). This is a
// client projection, not the backend TaskView; it is intentionally hand-defined.
export interface PlanTask {
  id: string;
  index: number;
  description: string;
  status: TaskStatus;
  output?: string | null;
  error?: string | null;
  // M4 self-correction projection.
  attempt?: number; // latest attempt number seen
  generation?: number; // plan generation (0 = original)
  reflection?: TaskReflection; // most recent verdict
}

// --- Episodic memory (M5) --------------------------------------------------

export type MemoryOutcome = Schemas["MemoryOutcome"];
export type MemorySource = Schemas["MemorySource"];
export type MemoryStatus = Schemas["MemoryStatus"];

// The API always serializes every field (the schema marks the defaulted ones
// optional); `Required` restores the precise shape the UI relies on while
// preserving the nullable unions on run_id / last_recalled_at.
export type MemoryView = Required<Schemas["MemoryView"]>;
